spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ithub_space}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:132455}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true

server.port=${PORT:8080}

spring.banner.charset=UTF-8

jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=86400000