spring.datasource.url=jdbc:postgresql://localhost:5432/ithub_space
spring.datasource.username=postgres
spring.datasource.password=132455

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.banner.charset=UTF-8